datasets:
  meld_caption:
    data_type: images
    build_info:
      ann_path: /scratch/data/bikash_rs/vivek/dataset/MELD.Raw/test_sent_emo.csv
      image_path: /scratch/data/bikash_rs/vivek/dataset/Meld_feat_ext